use crate::api::get_all_aws_regions;
use crossterm::{
    cursor,
    event::{self, Event, KeyCode, KeyModifiers},
    terminal::{disable_raw_mode, enable_raw_mode},
};
use std::fs;
use std::io::{self, Write};
use std::path::Path;
use std::process::{Command, Stdio};

pub const START_BLOCK: &str = "# --- DBD REGION CHANGER START ---";
pub const END_BLOCK: &str = "# --- DBD REGION CHANGER END ---";

#[cfg(windows)]
pub const HOSTS_PATH: &str = "C:\\Windows\\System32\\drivers\\etc\\hosts";
#[cfg(not(windows))]
pub const HOSTS_PATH: &str = "/etc/hosts";

fn is_russian() -> bool {
    let lang = std::env::var("LANG").unwrap_or_default().to_lowercase();
    let lc_all = std::env::var("LC_ALL").unwrap_or_default().to_lowercase();
    let lc_msg = std::env::var("LC_MESSAGES")
        .unwrap_or_default()
        .to_lowercase();

    lang.starts_with("ru") || lc_all.starts_with("ru") || lc_msg.starts_with("ru")
}

pub fn build_hosts_content(
    hosts_path: &Path,
    selected_aws_regions: Option<&[String]>,
) -> Result<String, std::io::Error> {
    let content = if hosts_path.exists() {
        fs::read_to_string(hosts_path)?
    } else {
        String::new()
    };

    let mut new_lines = Vec::new();
    let mut in_block = false;

    for line in content.lines() {
        let trimmed = line.trim();
        if trimmed == START_BLOCK {
            in_block = true;
            continue;
        }
        if trimmed == END_BLOCK {
            in_block = false;
            continue;
        }
        if !in_block {
            new_lines.push(line.to_string());
        }
    }

    // Clean trailing empty lines
    while let Some(last) = new_lines.last() {
        if last.trim().is_empty() {
            new_lines.pop();
        } else {
            break;
        }
    }

    let mut result = new_lines.join("\n");
    if !result.is_empty() {
        result.push('\n');
    }

    if let Some(selected) = selected_aws_regions {
        let all_regions = get_all_aws_regions();
        // If we are locking (selecting a subset of regions)
        if selected.len() < all_regions.len() {
            result.push_str(START_BLOCK);
            result.push_str("\n# Do not edit manually. Generated by dbdqueue CLI\n");

            for reg in all_regions {
                if !selected.iter().any(|s| s == reg) {
                    for ep in &[
                        format!("gamelift-ping.{}.api.aws", reg),
                        format!("gamelift.{}.api.aws", reg),
                        format!("gamelift-ping.{}.amazonaws.com", reg),
                        format!("gamelift.{}.amazonaws.com", reg),
                    ] {
                        result.push_str(&format!("0.0.0.0 {}\n::1 {}\n", ep, ep));
                    }
                }
            }
            result.push_str(END_BLOCK);
            result.push('\n');
        }
    }

    Ok(result)
}

#[derive(Debug, PartialEq, Eq, Clone)]
pub enum UpdateHostsResult {
    Updated,
    AlreadyUpToDate,
    ElevationFailed,
    Error(String),
}

#[cfg(windows)]
pub fn update_hosts(selected_aws_regions: Option<&[String]>, verbose: bool) -> UpdateHostsResult {
    let is_ru = is_russian();
    let hosts_path = Path::new(HOSTS_PATH);
    let new_content = match build_hosts_content(hosts_path, selected_aws_regions) {
        Ok(content) => content,
        Err(e) => {
            let err_msg = format!("{}", e);
            if verbose {
                let err_hdr = if is_ru {
                    "Ошибка создания содержимого hosts:"
                } else {
                    "Error generating hosts file content:"
                };
                eprintln!("\x1b[91m{}\x1b[0m {}", err_hdr, err_msg);
            }
            return UpdateHostsResult::Error(err_msg);
        }
    };

    let current_content = fs::read_to_string(hosts_path).unwrap_or_default();
    if current_content == new_content {
        if verbose {
            let msg = if is_ru {
                "Файл hosts уже актуален."
            } else {
                "Hosts file is already up to date."
            };
            println!("\x1b[92m{}\x1b[0m", msg);
        }
        return UpdateHostsResult::AlreadyUpToDate;
    }

    // Try to write directly (succeeds if running as Administrator)
    if fs::write(hosts_path, &new_content).is_ok() {
        if verbose {
            let msg = if is_ru {
                "Блокировка регионов успешно обновлена!"
            } else {
                "Successfully updated region locks!"
            };
            println!("\x1b[92m{}\x1b[0m", msg);
        }
        flush_dns_cache();
        return UpdateHostsResult::Updated;
    }

    // If writing fails, write to a temp file in AppConfig directory first
    if verbose {
        let req_msg = if is_ru {
            "Запрос прав Администратора для изменения файла hosts..."
        } else {
            "Requesting Administrator access to write to hosts file..."
        };
        println!("\x1b[93m{}\x1b[0m", req_msg);
    }

    let config_path = crate::config::get_config_path();
    let temp_path = config_path.with_file_name("hosts.tmp");
    if let Some(parent) = temp_path.parent() {
        let _ = fs::create_dir_all(parent);
    }

    if let Err(e) = fs::write(&temp_path, &new_content) {
        let err_msg = format!("{}", e);
        if verbose {
            let err_hdr = if is_ru {
                "Не удалось создать временный файл hosts:"
            } else {
                "Failed to create temporary hosts file:"
            };
            eprintln!("\x1b[91m{}\x1b[0m {}", err_hdr, err_msg);
        }
        return UpdateHostsResult::Error(err_msg);
    }

    // Trigger elevated PowerShell script to copy the hosts file over
    let ps_cmd = format!(
        "Start-Process powershell -ArgumentList '-NoProfile', '-WindowStyle', 'Hidden', '-Command', 'Copy-Item -Path \"{}\" -Destination \"{}\" -Force' -Verb RunAs -Wait",
        temp_path.to_string_lossy(),
        HOSTS_PATH
    );

    let status = Command::new("powershell")
        .args(["-NoProfile", "-Command", &ps_cmd])
        .status();

    // Clean up temp file
    let _ = fs::remove_file(&temp_path);

    match status {
        Ok(s) if s.success() => {
            if verbose {
                let msg = if is_ru {
                    "Блокировка регионов успешно обновлена!"
                } else {
                    "Successfully updated region locks!"
                };
                println!("\x1b[92m{}\x1b[0m", msg);
            }
            flush_dns_cache();
            UpdateHostsResult::Updated
        }
        _ => {
            if verbose {
                let err_msg = if is_ru {
                    "Не удалось обновить файл hosts: в повышении прав отказано или произошла ошибка."
                } else {
                    "Failed to update hosts file: elevation denied or failed."
                };
                eprintln!("\x1b[91m{}\x1b[0m", err_msg);
            }
            UpdateHostsResult::ElevationFailed
        }
    }
}

#[cfg(not(windows))]
pub fn update_hosts(selected_aws_regions: Option<&[String]>, verbose: bool) -> UpdateHostsResult {
    let is_ru = is_russian();
    let hosts_path = Path::new(HOSTS_PATH);
    let new_content = match build_hosts_content(hosts_path, selected_aws_regions) {
        Ok(content) => content,
        Err(e) => {
            let err_msg = format!("{}", e);
            if verbose {
                let err_hdr = if is_ru {
                    "Ошибка создания содержимого hosts:"
                } else {
                    "Error generating hosts file content:"
                };
                eprintln!("\x1b[91m{}\x1b[0m {}", err_hdr, err_msg);
            }
            return UpdateHostsResult::Error(err_msg);
        }
    };

    let current_content = fs::read_to_string(hosts_path).unwrap_or_default();
    if current_content == new_content {
        if verbose {
            let msg = if is_ru {
                "Файл hosts уже актуален."
            } else {
                "Hosts file is already up to date."
            };
            println!("\x1b[92m{}\x1b[0m", msg);
        }
        return UpdateHostsResult::AlreadyUpToDate;
    }

    if verbose {
        let req_msg = if is_ru {
            "Запрос прав root для изменения /etc/hosts..."
        } else {
            "Requesting write access to /etc/hosts..."
        };
        println!("\x1b[93m{}\x1b[0m", req_msg);
    }

    let mut child = match Command::new("pkexec")
        .args(["tee", HOSTS_PATH])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
    {
        Ok(child) => child,
        Err(e) => {
            let err_msg = format!("{}", e);
            if verbose {
                let err_hdr = if is_ru {
                    "Ошибка запуска pkexec:"
                } else {
                    "Error executing pkexec:"
                };
                eprintln!("\x1b[91m{}\x1b[0m {}", err_hdr, err_msg);
            }
            return UpdateHostsResult::Error(err_msg);
        }
    };

    if let Some(mut stdin) = child.stdin.take()
        && let Err(e) = stdin.write_all(new_content.as_bytes())
    {
        let err_msg = format!("{}", e);
        if verbose {
            let err_hdr = if is_ru {
                "Ошибка записи в stdin pkexec:"
            } else {
                "Error writing to pkexec stdin:"
            };
            eprintln!("\x1b[91m{}\x1b[0m {}", err_hdr, err_msg);
        }
        return UpdateHostsResult::Error(err_msg);
    }

    match child.wait_with_output() {
        Ok(output) => {
            if output.status.success() {
                if verbose {
                    let msg = if is_ru {
                        "Блокировка регионов успешно обновлена!"
                    } else {
                        "Successfully updated region locks!"
                    };
                    println!("\x1b[92m{}\x1b[0m", msg);
                }
                flush_dns_cache();
                UpdateHostsResult::Updated
            } else {
                let err_msg = String::from_utf8_lossy(&output.stderr).to_string();
                if verbose {
                    let fail_hdr = if is_ru {
                        "Не удалось записать в /etc/hosts"
                    } else {
                        "Failed to write to /etc/hosts"
                    };
                    eprintln!(
                        "\x1b[91m{} (code {:?}):\x1b[0m\n{}",
                        fail_hdr,
                        output.status.code(),
                        err_msg.trim()
                    );
                }
                UpdateHostsResult::Error(err_msg)
            }
        }
        Err(e) => {
            let err_msg = format!("{}", e);
            if verbose {
                let err_hdr = if is_ru {
                    "Ошибка ожидания pkexec:"
                } else {
                    "Error waiting for pkexec:"
                };
                eprintln!("\x1b[91m{}\x1b[0m {}", err_hdr, err_msg);
            }
            UpdateHostsResult::Error(err_msg)
        }
    }
}

pub fn flush_dns_cache() {
    #[cfg(windows)]
    {
        let _ = Command::new("ipconfig")
            .arg("/flushdns")
            .stdout(Stdio::null())
            .stderr(Stdio::null())
            .status();
    }
    #[cfg(not(windows))]
    {
        let res = Command::new("resolvectl")
            .arg("flush-caches")
            .stdout(Stdio::null())
            .stderr(Stdio::null())
            .status();

        if res.is_ok() {
            return;
        }

        let _ = Command::new("systemd-resolve")
            .arg("--flush-caches")
            .stdout(Stdio::null())
            .stderr(Stdio::null())
            .status();
    }
}

fn run_interactive_menu(
    title: &str,
    options: &[(String, String)],
    initial_selected: &[String],
    instructions: &str,
) -> Option<Vec<String>> {
    let mut selected: Vec<bool> = options
        .iter()
        .map(|(_, val)| initial_selected.contains(val))
        .collect();
    let mut cursor_pos = 0;

    let mut stdout = io::stdout();
    enable_raw_mode().ok()?;

    // Drain any leftover events (e.g. Enter key from starting the command)
    while event::poll(std::time::Duration::from_millis(50)).unwrap_or(false) {
        let _ = event::read();
    }

    let _ = crossterm::execute!(stdout, cursor::Hide);
    write!(stdout, "\x1b[H\x1b[2J").ok();
    stdout.flush().ok();

    loop {
        write!(stdout, "\x1b[H\x1b[2J").ok();
        write!(stdout, "\x1b[1m\x1b[91m{}\x1b[0m\r\n", title).ok();
        write!(stdout, "{}\r\n\r\n", instructions).ok();

        for (i, (display, _)) in options.iter().enumerate() {
            let checked = if selected[i] { "[*]" } else { "[ ]" };
            let color = if selected[i] { "\x1b[92m" } else { "\x1b[90m" };

            if i == cursor_pos {
                write!(stdout, " \x1b[7m {} {} \x1b[27m\r\n", checked, display).ok();
            } else {
                write!(stdout, " {} {} {}\x1b[0m\r\n", color, checked, display).ok();
            }
        }
        stdout.flush().ok();

        if let Ok(Event::Key(key)) = event::read() {
            if key.kind != crossterm::event::KeyEventKind::Press {
                continue;
            }
            match key.code {
                KeyCode::Up => {
                    cursor_pos = (cursor_pos + options.len() - 1) % options.len();
                }
                KeyCode::Down => {
                    cursor_pos = (cursor_pos + 1) % options.len();
                }
                KeyCode::Char(' ') => {
                    selected[cursor_pos] = !selected[cursor_pos];
                }
                KeyCode::Enter => {
                    break;
                }
                KeyCode::Esc => {
                    let cancel_msg = if is_russian() {
                        "\r\n\x1b[91mОтменено.\x1b[0m\r\n"
                    } else {
                        "\r\n\x1b[91mCancelled.\x1b[0m\r\n"
                    };
                    disable_raw_mode().ok();
                    let _ = crossterm::execute!(stdout, cursor::Show);
                    write!(stdout, "{}", cancel_msg).ok();
                    stdout.flush().ok();
                    return None;
                }
                KeyCode::Char('c') if key.modifiers.contains(KeyModifiers::CONTROL) => {
                    let cancel_msg = if is_russian() {
                        "\r\n\x1b[91mОтменено.\x1b[0m\r\n"
                    } else {
                        "\r\n\x1b[91mCancelled.\x1b[0m\r\n"
                    };
                    disable_raw_mode().ok();
                    let _ = crossterm::execute!(stdout, cursor::Show);
                    write!(stdout, "{}", cancel_msg).ok();
                    stdout.flush().ok();
                    return None;
                }
                _ => {}
            }
        }
    }

    disable_raw_mode().ok();
    let _ = crossterm::execute!(stdout, cursor::Show);
    stdout.flush().ok();

    let result = options
        .iter()
        .enumerate()
        .filter(|(i, _)| selected[*i])
        .map(|(_, (_, val))| val.clone())
        .collect();
    Some(result)
}

pub fn interactive_lock_menu(current_locked: &[String]) -> Option<Vec<String>> {
    let is_ru = is_russian();
    let queues = crate::api::fetch_queue_times()
        .map(|(q, _)| q)
        .unwrap_or_default();
    let disabled = crate::api::get_disabled_aws_regions(&queues);
    let pings = crate::ping::measure_all_regions_ping();
    let mut aws_regions: Vec<&'static str> = crate::api::get_all_aws_regions()
        .into_iter()
        .filter(|reg| !disabled.contains(*reg))
        .collect();
    aws_regions.sort_by(|&a, &b| {
        let a_ping = pings.get(a).copied().unwrap_or(u32::MAX);
        let b_ping = pings.get(b).copied().unwrap_or(u32::MAX);
        a_ping.cmp(&b_ping).then_with(|| {
            let aws_to_api = crate::api::get_aws_to_api();
            let a_name = aws_to_api.get(a).unwrap_or(&a);
            let b_name = aws_to_api.get(b).unwrap_or(&b);
            a_name.cmp(b_name)
        })
    });

    let aws_to_api = crate::api::get_aws_to_api();
    let aws_to_flag = crate::api::get_aws_to_flag();

    let options: Vec<(String, String)> = aws_regions
        .iter()
        .map(|code| {
            let name = aws_to_api.get(*code).unwrap_or(code);
            let flag = aws_to_flag.get(*code).unwrap_or(&"");
            let flag_str = if flag.is_empty() {
                String::new()
            } else {
                format!("{} ", flag)
            };
            let ping_str = if let Some(&ms) = pings.get(*code) {
                format!(" - {} ms", ms)
            } else {
                String::new()
            };
            (
                format!("{}{}{} ({}){}", flag_str, name, "", code, ping_str),
                code.to_string(),
            )
        })
        .collect();

    let title = if is_ru {
        "Блокировка регионов"
    } else {
        "Region Locker"
    };
    let instructions = if is_ru {
        "\x1b[91m[↑↓]\x1b[0m Выбор  \x1b[91m[Пробел]\x1b[0m Вкл/Выкл  \x1b[91m[Enter]\x1b[0m Сохранить  \x1b[91m[Esc]\x1b[0m Отмена"
    } else {
        "\x1b[91m[↑↓]\x1b[0m Select  \x1b[91m[Space]\x1b[0m Toggle  \x1b[91m[Enter]\x1b[0m Save  \x1b[91m[Esc]\x1b[0m Cancel"
    };

    run_interactive_menu(title, &options, current_locked, instructions)
}

pub fn interactive_priority_menu(current_priority: &[String]) -> Option<Vec<String>> {
    let queues = crate::api::fetch_queue_times()
        .map(|(q, _)| q)
        .unwrap_or_default();
    let disabled = crate::api::get_disabled_aws_regions(&queues);
    let api_to_aws = crate::api::get_api_to_aws();
    let mut regions: Vec<String> = api_to_aws
        .iter()
        .filter(|(_, code)| !disabled.contains(**code))
        .map(|(name, _)| name.to_string())
        .collect();
    regions.sort();

    let options: Vec<(String, String)> = regions.iter().map(|r| (r.clone(), r.clone())).collect();

    let is_ru = is_russian();
    let title = if is_ru {
        "Приоритетные регионы"
    } else {
        "Priority Regions"
    };
    let instructions = if is_ru {
        "\x1b[91m[↑↓]\x1b[0m Выбор  \x1b[91m[Пробел]\x1b[0m Вкл/Выкл  \x1b[91m[Enter]\x1b[0m Сохранить  \x1b[91m[Esc]\x1b[0m Отмена"
    } else {
        "\x1b[91m[↑↓]\x1b[0m Select  \x1b[91m[Space]\x1b[0m Toggle  \x1b[91m[Enter]\x1b[0m Save  \x1b[91m[Esc]\x1b[0m Cancel"
    };

    run_interactive_menu(title, &options, current_priority, instructions)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_build_hosts() {
        let test_file_path = Path::new("test_hosts_tmp");

        let initial = "127.0.0.1 localhost\n::1 localhost\n";
        fs::write(test_file_path, initial).unwrap();

        let selected = vec!["eu-central-1".to_string(), "eu-west-1".to_string()];
        let content = build_hosts_content(test_file_path, Some(&selected)).unwrap();

        assert!(content.contains("127.0.0.1 localhost"));
        assert!(content.contains(START_BLOCK));
        assert!(content.contains(END_BLOCK));

        // Whitelisted regions should NOT be blocked
        assert!(!content.contains("gamelift-ping.eu-central-1.api.aws"));
        assert!(!content.contains("gamelift-ping.eu-west-1.api.aws"));

        // Non-whitelisted regions SHOULD be blocked
        assert!(content.contains("0.0.0.0 gamelift-ping.us-east-1.api.aws"));
        assert!(content.contains("::1 gamelift-ping.us-east-1.api.aws"));

        // Unlocking
        let unlocked_content = build_hosts_content(test_file_path, None).unwrap();
        assert!(unlocked_content.contains("127.0.0.1 localhost"));
        assert!(!unlocked_content.contains(START_BLOCK));
        assert!(!unlocked_content.contains("gamelift-ping.us-east-1.api.aws"));

        let _ = fs::remove_file(test_file_path);
    }
}
