use std::fs;
use std::io::Write;
use std::path::Path;
use std::process::{Command, Stdio};
use crate::api::get_all_aws_regions;

const START_BLOCK: &str = "# --- DBD REGION CHANGER START ---";
const END_BLOCK: &str = "# --- DBD REGION CHANGER END ---";
pub const HOSTS_PATH: &str = "/etc/hosts";

pub fn build_hosts_content(hosts_path: &Path, selected_aws_regions: Option<&[String]>) -> Result<String, std::io::Error> {
    let content = if hosts_path.exists() {
        fs::read_to_string(hosts_path)?
    } else {
        String::new()
    };

    let mut new_lines = Vec::new();
    let mut in_block = false;

    for line in content.lines() {
        let trimmed = line.trim();
        if trimmed == START_BLOCK {
            in_block = true;
            continue;
        }
        if trimmed == END_BLOCK {
            in_block = false;
            continue;
        }
        if !in_block {
            new_lines.push(line.to_string());
        }
    }

    // Clean trailing empty lines
    while let Some(last) = new_lines.last() {
        if last.trim().is_empty() {
            new_lines.pop();
        } else {
            break;
        }
    }
    
    let mut result = new_lines.join("\n");
    if !result.is_empty() {
        result.push('\n');
    }

    if let Some(selected) = selected_aws_regions {
        let all_regions = get_all_aws_regions();
        // If we are locking (selecting a subset of regions)
        if selected.len() < all_regions.len() {
            result.push_str(START_BLOCK);
            result.push_str("\n# Do not edit manually. Generated by dbdqueue CLI\n");
            
            for reg in all_regions {
                if !selected.iter().any(|s| s == reg) {
                    for ep in &[
                        format!("gamelift-ping.{}.api.aws", reg),
                        format!("gamelift.{}.api.aws", reg),
                        format!("gamelift-ping.{}.amazonaws.com", reg),
                        format!("gamelift.{}.amazonaws.com", reg),
                    ] {
                        result.push_str(&format!("0.0.0.0 {}\n::1 {}\n", ep, ep));
                    }
                }
            }
            result.push_str(END_BLOCK);
            result.push('\n');
        }
    }

    Ok(result)
}

pub fn update_hosts(selected_aws_regions: Option<&[String]>) {
    let hosts_path = Path::new(HOSTS_PATH);
    let new_content = match build_hosts_content(hosts_path, selected_aws_regions) {
        Ok(content) => content,
        Err(e) => {
            eprintln!("\x1b[91mError generating hosts file content:\x1b[0m {}", e);
            return;
        }
    };

    let current_content = fs::read_to_string(hosts_path).unwrap_or_default();
    if current_content == new_content {
        println!("\x1b[92mHosts file is already up to date.\x1b[0m");
        return;
    }

    println!("\x1b[93mRequesting write access to /etc/hosts...\x1b[0m");
    let mut child = match Command::new("pkexec")
        .args(["tee", HOSTS_PATH])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
    {
        Ok(child) => child,
        Err(e) => {
            eprintln!("\x1b[91mError executing pkexec:\x1b[0m {}", e);
            return;
        }
    };

    if let Some(mut stdin) = child.stdin.take()
        && let Err(e) = stdin.write_all(new_content.as_bytes()) {
            eprintln!("\x1b[91mError writing to pkexec stdin:\x1b[0m {}", e);
            return;
        }

    match child.wait_with_output() {
        Ok(output) => {
            if output.status.success() {
                println!("\x1b[92mSuccessfully updated region locks!\x1b[0m");
                flush_dns_cache();
            } else {
                let err_msg = String::from_utf8_lossy(&output.stderr);
                eprintln!(
                    "\x1b[91mFailed to write to /etc/hosts (code {:?}):\x1b[0m\n{}",
                    output.status.code(),
                    err_msg.trim()
                );
            }
        }
        Err(e) => {
            eprintln!("\x1b[91mError waiting for pkexec:\x1b[0m {}", e);
        }
    }
}

fn flush_dns_cache() {
    let res = Command::new("resolvectl")
        .arg("flush-caches")
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status();
        
    if res.is_ok() {
        return;
    }
    
    let _ = Command::new("systemd-resolve")
        .arg("--flush-caches")
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status();
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_build_hosts() {
        let test_file_path = Path::new("test_hosts_tmp");
        
        let initial = "127.0.0.1 localhost\n::1 localhost\n";
        fs::write(test_file_path, initial).unwrap();
        
        let selected = vec!["eu-central-1".to_string(), "eu-west-1".to_string()];
        let content = build_hosts_content(test_file_path, Some(&selected)).unwrap();
        
        assert!(content.contains("127.0.0.1 localhost"));
        assert!(content.contains(START_BLOCK));
        assert!(content.contains(END_BLOCK));
        
        assert!(!content.contains("gamelift-ping.eu-central-1.api.aws"));
        assert!(!content.contains("gamelift-ping.eu-west-1.api.aws"));
        
        assert!(content.contains("0.0.0.0 gamelift-ping.us-east-1.api.aws"));
        
        let unlocked_content = build_hosts_content(test_file_path, None).unwrap();
        assert!(unlocked_content.contains("127.0.0.1 localhost"));
        assert!(!unlocked_content.contains(START_BLOCK));
        assert!(!unlocked_content.contains("gamelift-ping.us-east-1.api.aws"));
        
        let _ = fs::remove_file(test_file_path);
    }
}

