use crate::api::get_all_aws_regions;
use crossterm::{
    cursor,
    event::{self, Event, KeyCode, KeyModifiers},
    terminal::{EnterAlternateScreen, LeaveAlternateScreen, disable_raw_mode, enable_raw_mode},
};
use ratatui::{Terminal, backend::CrosstermBackend};
use std::fs;
use std::io;
use std::path::Path;
use std::process::{Command, Stdio};
use std::time::Duration;

pub const START_BLOCK: &str = "# --- DBD REGION CHANGER START ---";
pub const END_BLOCK: &str = "# --- DBD REGION CHANGER END ---";

#[cfg(windows)]
pub const HOSTS_PATH: &str = "C:\\Windows\\System32\\drivers\\etc\\hosts";
#[cfg(not(windows))]
pub const HOSTS_PATH: &str = "/etc/hosts";

fn is_russian() -> bool {
    let lang = std::env::var("LANG").unwrap_or_default().to_lowercase();
    let lc_all = std::env::var("LC_ALL").unwrap_or_default().to_lowercase();
    let lc_msg = std::env::var("LC_MESSAGES")
        .unwrap_or_default()
        .to_lowercase();

    lang.starts_with("ru") || lc_all.starts_with("ru") || lc_msg.starts_with("ru")
}

pub fn build_hosts_content(
    hosts_path: &Path,
    selected_aws_regions: Option<&[String]>,
) -> Result<String, std::io::Error> {
    let content = if hosts_path.exists() {
        fs::read_to_string(hosts_path)?
    } else {
        String::new()
    };

    let mut new_lines = Vec::new();
    let mut in_block = false;

    for line in content.lines() {
        let trimmed = line.trim();
        if trimmed == START_BLOCK {
            in_block = true;
            continue;
        }
        if trimmed == END_BLOCK {
            in_block = false;
            continue;
        }
        if !in_block {
            new_lines.push(line.to_string());
        }
    }

    // Clean trailing empty lines
    while let Some(last) = new_lines.last() {
        if last.trim().is_empty() {
            new_lines.pop();
        } else {
            break;
        }
    }

    let mut result = new_lines.join("\n");
    if !result.is_empty() {
        result.push('\n');
    }

    if let Some(selected) = selected_aws_regions {
        let all_regions = get_all_aws_regions();
        // If we are locking (selecting a subset of regions)
        if selected.len() < all_regions.len() {
            result.push_str(START_BLOCK);
            result.push_str("\n# Do not edit manually. Generated by dbdqueue CLI\n");

            for reg in all_regions {
                if !selected.iter().any(|s| s == reg) {
                    for ep in &[
                        format!("gamelift-ping.{}.api.aws", reg),
                        format!("gamelift.{}.api.aws", reg),
                        format!("gamelift-ping.{}.amazonaws.com", reg),
                        format!("gamelift.{}.amazonaws.com", reg),
                    ] {
                        result.push_str(&format!("0.0.0.0 {}\n::1 {}\n", ep, ep));
                    }
                }
            }
            result.push_str(END_BLOCK);
            result.push('\n');
        }
    }

    Ok(result)
}

#[derive(Debug, PartialEq, Eq, Clone)]
pub enum UpdateHostsResult {
    Updated,
    AlreadyUpToDate,
    #[allow(dead_code)]
    ElevationFailed,
    Error(String),
}

#[cfg(windows)]
pub fn update_hosts(selected_aws_regions: Option<&[String]>, verbose: bool) -> UpdateHostsResult {
    let is_ru = is_russian();
    let hosts_path = Path::new(HOSTS_PATH);
    let new_content = match build_hosts_content(hosts_path, selected_aws_regions) {
        Ok(content) => content,
        Err(e) => {
            let err_msg = format!("{}", e);
            if verbose {
                let err_hdr = if is_ru {
                    "Ошибка создания содержимого hosts:"
                } else {
                    "Error generating hosts file content:"
                };
                eprintln!("\x1b[91m{}\x1b[0m {}", err_hdr, err_msg);
            }
            return UpdateHostsResult::Error(err_msg);
        }
    };

    let current_content = fs::read_to_string(hosts_path).unwrap_or_default();
    if current_content == new_content {
        if verbose {
            let msg = if is_ru {
                "Файл hosts уже актуален."
            } else {
                "Hosts file is already up to date."
            };
            println!("\x1b[92m{}\x1b[0m", msg);
        }
        return UpdateHostsResult::AlreadyUpToDate;
    }

    // Try to write directly (succeeds if running as Administrator)
    if fs::write(hosts_path, &new_content).is_ok() {
        if verbose {
            let msg = if is_ru {
                "Блокировка регионов успешно обновлена!"
            } else {
                "Successfully updated region locks!"
            };
            println!("\x1b[92m{}\x1b[0m", msg);
        }
        flush_dns_cache();
        return UpdateHostsResult::Updated;
    }

    // If writing fails, write to a temp file in AppConfig directory first
    if verbose {
        let req_msg = if is_ru {
            "Запрос прав Администратора для изменения файла hosts..."
        } else {
            "Requesting Administrator access to write to hosts file..."
        };
        println!("\x1b[93m{}\x1b[0m", req_msg);
    }

    let config_path = crate::config::get_config_path();
    let temp_path = config_path.with_file_name("hosts.tmp");
    if let Some(parent) = temp_path.parent() {
        let _ = fs::create_dir_all(parent);
    }

    if let Err(e) = fs::write(&temp_path, &new_content) {
        let err_msg = format!("{}", e);
        if verbose {
            let err_hdr = if is_ru {
                "Не удалось создать временный файл hosts:"
            } else {
                "Failed to create temporary hosts file:"
            };
            eprintln!("\x1b[91m{}\x1b[0m {}", err_hdr, err_msg);
        }
        return UpdateHostsResult::Error(err_msg);
    }

    // Trigger elevated PowerShell script to copy the hosts file over
    let ps_cmd = format!(
        "Start-Process powershell -ArgumentList '-NoProfile', '-WindowStyle', 'Hidden', '-Command', 'Copy-Item -Path \"{}\" -Destination \"{}\" -Force' -Verb RunAs -Wait",
        temp_path.to_string_lossy(),
        HOSTS_PATH
    );

    let status = Command::new("powershell")
        .args(["-NoProfile", "-Command", &ps_cmd])
        .status();

    // Clean up temp file
    let _ = fs::remove_file(&temp_path);

    match status {
        Ok(s) if s.success() => {
            if verbose {
                let msg = if is_ru {
                    "Блокировка регионов успешно обновлена!"
                } else {
                    "Successfully updated region locks!"
                };
                println!("\x1b[92m{}\x1b[0m", msg);
            }
            flush_dns_cache();
            UpdateHostsResult::Updated
        }
        _ => {
            if verbose {
                let err_msg = if is_ru {
                    "Не удалось обновить файл hosts: в повышении прав отказано или произошла ошибка."
                } else {
                    "Failed to update hosts file: elevation denied or failed."
                };
                eprintln!("\x1b[91m{}\x1b[0m", err_msg);
            }
            UpdateHostsResult::ElevationFailed
        }
    }
}

#[cfg(not(windows))]
pub fn update_hosts(selected_aws_regions: Option<&[String]>, verbose: bool) -> UpdateHostsResult {
    let is_ru = is_russian();
    let hosts_path = Path::new(HOSTS_PATH);
    let new_content = match build_hosts_content(hosts_path, selected_aws_regions) {
        Ok(content) => content,
        Err(e) => {
            let err_msg = format!("{}", e);
            if verbose {
                let err_hdr = if is_ru {
                    "Ошибка создания содержимого hosts:"
                } else {
                    "Error generating hosts file content:"
                };
                eprintln!("\x1b[91m{}\x1b[0m {}", err_hdr, err_msg);
            }
            return UpdateHostsResult::Error(err_msg);
        }
    };

    let current_content = fs::read_to_string(hosts_path).unwrap_or_default();
    if current_content == new_content {
        if verbose {
            let msg = if is_ru {
                "Файл hosts уже актуален."
            } else {
                "Hosts file is already up to date."
            };
            println!("\x1b[92m{}\x1b[0m", msg);
        }
        return UpdateHostsResult::AlreadyUpToDate;
    }

    if verbose {
        let req_msg = if is_ru {
            "Запрос прав root для изменения /etc/hosts..."
        } else {
            "Requesting write access to /etc/hosts..."
        };
        println!("\x1b[93m{}\x1b[0m", req_msg);
    }

    let mut child = match Command::new("pkexec")
        .args(["tee", HOSTS_PATH])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
    {
        Ok(child) => child,
        Err(e) => {
            let err_msg = format!("{}", e);
            if verbose {
                let err_hdr = if is_ru {
                    "Ошибка запуска pkexec:"
                } else {
                    "Error executing pkexec:"
                };
                eprintln!("\x1b[91m{}\x1b[0m {}", err_hdr, err_msg);
            }
            return UpdateHostsResult::Error(err_msg);
        }
    };

    if let Some(mut stdin) = child.stdin.take()
        && let Err(e) = stdin.write_all(new_content.as_bytes())
    {
        let err_msg = format!("{}", e);
        if verbose {
            let err_hdr = if is_ru {
                "Ошибка записи в stdin pkexec:"
            } else {
                "Error writing to pkexec stdin:"
            };
            eprintln!("\x1b[91m{}\x1b[0m {}", err_hdr, err_msg);
        }
        return UpdateHostsResult::Error(err_msg);
    }

    match child.wait_with_output() {
        Ok(output) => {
            if output.status.success() {
                if verbose {
                    let msg = if is_ru {
                        "Блокировка регионов успешно обновлена!"
                    } else {
                        "Successfully updated region locks!"
                    };
                    println!("\x1b[92m{}\x1b[0m", msg);
                }
                flush_dns_cache();
                UpdateHostsResult::Updated
            } else {
                let err_msg = String::from_utf8_lossy(&output.stderr).to_string();
                if verbose {
                    let fail_hdr = if is_ru {
                        "Не удалось записать в /etc/hosts"
                    } else {
                        "Failed to write to /etc/hosts"
                    };
                    eprintln!(
                        "\x1b[91m{} (code {:?}):\x1b[0m\n{}",
                        fail_hdr,
                        output.status.code(),
                        err_msg.trim()
                    );
                }
                UpdateHostsResult::Error(err_msg)
            }
        }
        Err(e) => {
            let err_msg = format!("{}", e);
            if verbose {
                let err_hdr = if is_ru {
                    "Ошибка ожидания pkexec:"
                } else {
                    "Error waiting for pkexec:"
                };
                eprintln!("\x1b[91m{}\x1b[0m {}", err_hdr, err_msg);
            }
            UpdateHostsResult::Error(err_msg)
        }
    }
}

pub fn flush_dns_cache() {
    #[cfg(windows)]
    {
        let _ = Command::new("ipconfig")
            .arg("/flushdns")
            .stdout(Stdio::null())
            .stderr(Stdio::null())
            .status();
    }
    #[cfg(not(windows))]
    {
        let res = Command::new("resolvectl")
            .arg("flush-caches")
            .stdout(Stdio::null())
            .stderr(Stdio::null())
            .status();

        if res.is_ok() {
            return;
        }

        let _ = Command::new("systemd-resolve")
            .arg("--flush-caches")
            .stdout(Stdio::null())
            .stderr(Stdio::null())
            .status();
    }
}

pub fn interactive_lock_menu(current_locked: &[String]) -> Option<Vec<String>> {
    let is_ru = is_russian();
    let queues = crate::api::fetch_queue_times()
        .map(|(q, _)| q)
        .unwrap_or_default();
    let pings = crate::ping::measure_all_regions_ping();

    let lang = if is_ru {
        crate::config::Language::Ru
    } else {
        crate::config::Language::En
    };
    let mut app = crate::app::App::new(
        crate::config::SortOrder::Default,
        crate::config::GameMode::Standard,
        current_locked.to_vec(),
        lang,
        None,
    );
    app.queues = queues;
    app.pings = pings;
    app.open_lock_modal();

    enable_raw_mode().ok()?;
    let mut stdout = io::stdout();
    crossterm::execute!(stdout, EnterAlternateScreen, cursor::Hide).ok()?;
    let backend = CrosstermBackend::new(stdout);
    let mut terminal = Terminal::new(backend).ok()?;

    // Drain any leftover input events
    while event::poll(Duration::from_millis(50)).unwrap_or(false) {
        let _ = event::read();
    }

    let mut applied = false;
    let mut cancelled = false;

    loop {
        terminal
            .draw(|f| {
                let modal_area = if f.area().width <= 80 || f.area().height <= 24 {
                    f.area()
                } else {
                    crate::ui::centered_rect(70, 80, f.area())
                };
                crate::ui::draw_lock_modal(f, &app, modal_area);
            })
            .ok();

        match event::read() {
            Ok(Event::Key(key)) => {
                if key.kind != crossterm::event::KeyEventKind::Press {
                    continue;
                }
                match key.code {
                    KeyCode::Up | KeyCode::Char('k') => {
                        app.lock_modal_up();
                    }
                    KeyCode::Down | KeyCode::Char('j') => {
                        app.lock_modal_down();
                    }
                    KeyCode::Char(' ') => {
                        app.lock_modal_toggle();
                    }
                    KeyCode::Enter => {
                        applied = true;
                        break;
                    }
                    KeyCode::Esc | KeyCode::Char('q') => {
                        cancelled = true;
                        break;
                    }
                    KeyCode::Char('c') if key.modifiers.contains(KeyModifiers::CONTROL) => {
                        cancelled = true;
                        break;
                    }
                    _ => {}
                }
            }
            Ok(Event::Resize(_, _)) => {
                // Buffer resize handled automatically by Ratatui on next draw
            }
            _ => {}
        }
    }

    disable_raw_mode().ok();
    crossterm::execute!(terminal.backend_mut(), LeaveAlternateScreen, cursor::Show).ok();

    if cancelled || !applied {
        let cancel_msg = if is_ru {
            "Отменено."
        } else {
            "Cancelled."
        };
        eprintln!("\x1b[91m{}\x1b[0m", cancel_msg);
        return None;
    }

    let mut res = app.lock_modal_selected;
    res.sort();
    Some(res)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_build_hosts() {
        let test_file_path = Path::new("test_hosts_tmp");

        let initial = "127.0.0.1 localhost\n::1 localhost\n";
        fs::write(test_file_path, initial).unwrap();

        let selected = vec!["eu-central-1".to_string(), "eu-west-1".to_string()];
        let content = build_hosts_content(test_file_path, Some(&selected)).unwrap();

        assert!(content.contains("127.0.0.1 localhost"));
        assert!(content.contains(START_BLOCK));
        assert!(content.contains(END_BLOCK));

        // Whitelisted regions should NOT be blocked
        assert!(!content.contains("gamelift-ping.eu-central-1.api.aws"));
        assert!(!content.contains("gamelift-ping.eu-west-1.api.aws"));

        // Non-whitelisted regions SHOULD be blocked
        assert!(content.contains("0.0.0.0 gamelift-ping.us-east-1.api.aws"));
        assert!(content.contains("::1 gamelift-ping.us-east-1.api.aws"));

        // Unlocking
        let unlocked_content = build_hosts_content(test_file_path, None).unwrap();
        assert!(unlocked_content.contains("127.0.0.1 localhost"));
        assert!(!unlocked_content.contains(START_BLOCK));
        assert!(!unlocked_content.contains("gamelift-ping.us-east-1.api.aws"));

        let _ = fs::remove_file(test_file_path);
    }
}
